services:
  pypi-server:
    build: 
      context: .
      dockerfile: DOCKERFILE.pypi
    container_name: pypiserver    
    ports:
      - "8080:8080"
    networks:
      - pypi-network

  dev-client:
    build:
      context: .
      dockerfile: DOCKERFILE.devenv
    container_name: developer

    networks:
      - pypi-network

networks:
  pypi-network:
    driver: bridge
