FROM python:3.9-slim

RUN apt-get update && apt-get install -y
RUN pip install --upgrade pip
# Set working directory
WORKDIR /app

# Copy the requirements.txt (which specifies using the local PyPI server)
COPY requirements.txt /app/requirements.txt
COPY app.py /app/
# Copy the shell script that installs the requirements
COPY install_requirements.sh /app/install_requirements.sh

# Make the shell script executable
RUN chmod +x /app/install_requirements.sh

CMD ["/app/install_requirements.sh"] 
