
# https://pypi.org/project/pypiserver/


FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    curl

RUN pip install pypiserver

# Create the directory for the PyPI repository
RUN mkdir -p /srv/pypi/packages

# Copy the package directory into the container
COPY ./package/ /srv/pypi/packages

WORKDIR /srv/pypi/packages

RUN python3 -m pip install --upgrade build

RUN python3 -m build

EXPOSE 8080 80

WORKDIR /srv/pypi/packages

CMD ["sh", "-c", "pypi-server run -p 8080 /srv/pypi/packages/"]
